apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`{{ .Values.ingress.pathPrefix }}`)
      kind: Rule
      middlewares:
        - name: {{ .Chart.Name }}-strip-prefix
      services:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
          scheme: http
  tls:
    certResolver: default
