{{- $name := .Release.Name -}}
{{- $ns := .Release.Namespace -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          args: {{ toYaml .Values.image.args | nindent 12 }}
          env:
            - name: DB_USERNAME
              value: "{{ .Values.env.DB_USERNAME }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: DB_URL
              value: "{{ .Values.env.DB_URL }}"
            - name: DB_SHOW_SQL
              value: "{{ .Values.env.DB_SHOW_SQL }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: IMAGE_PATH
              value: "{{ .Values.env.IMAGE_PATH }}"

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - port: 80
      targetPort: "{{ .Values.env.SERVER_PORT }}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
    traefik.ingress.kubernetes.io/router.middlewares: "{{ $ns }}-{{ $name }}-strip-prefix@kubernetescrd"
spec:
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: {{.Values.ingress.pathPrefix}}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: 80
  tls:
    - hosts:
        - {{.Values.ingress.host}}
