apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-mysql