apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.username }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "{{ .Values.mysql.resources.requests.memory }}"
              cpu: "{{ .Values.mysql.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.mysql.resources.limits.memory }}"
              cpu: "{{ .Values.mysql.resources.limits.cpu }}"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-mysql-pvc